
export const calculators = [
    {
        slug: "pos-komisyon-hesaplama",
        icon: "💳",
        title: "POS Komisyon Hesaplama",
        description: "POS komisyon oranları ve net geçecek tutarı hesaplayın",
        category: "finans",
        categoryLabel: "Finans",
    },
    {
        slug: "mtv-hesaplama",
        icon: "🚗",
        title: "MTV Hesaplama",
        description: "2026 Motorlu Taşıtlar Vergisi hesaplaması",
        category: "finans",
        categoryLabel: "Finans",
    },
    {
        slug: "yuzde-hesaplama",
        icon: "📊",
        title: "Yüzde Hesaplama",
        description: "Bir sayının yüzdesini veya yüzde değişimini hesaplayın",
        category: "genel",
        categoryLabel: "Genel",
    },
    {
        slug: "kdv-hesaplama",
        icon: "🧾",
        title: "KDV Hesaplama",
        description: "KDV dahil/hariç fiyat ve KDV tutarını bulun",
        category: "finans",
        categoryLabel: "Finans",
    },
    {
        slug: "yas-hesaplama",
        icon: "🎂",
        title: "Yaş Hesaplama",
        description: "Doğum tarihinizden yaşınızı gün gün hesaplayın",
        category: "genel",
        categoryLabel: "Genel",
    },
    {
        slug: "maas-hesaplama",
        icon: "💰",
        title: "Maaş Hesaplama",
        description: "Net ve brüt maaş dönüşümü yapın",
        category: "finans",
        categoryLabel: "Finans",
    },
    {
        slug: "kredi-hesaplama",
        icon: "🏦",
        title: "Kredi Hesaplama",
        description: "Aylık taksit ve toplam ödeme tutarını öğrenin",
        category: "finans",
        categoryLabel: "Finans",
    },
    {
        slug: "desi-hesaplama",
        icon: "📦",
        title: "Desi Hesaplama",
        description: "Kargo desi ölçümü ve fiyat tahmini",
        category: "e-ticaret",
        categoryLabel: "E-Ticaret",
    },
];

export const categories = [
    {
        id: "finans",
        name: "Finans",
        icon: "💰",
        description: "Maaş, kredi, KDV ve vergi hesaplamaları",
        color: "from-emerald-500 to-teal-600",
        count: 8,
    },
    {
        id: "genel",
        name: "Genel",
        icon: "🔢",
        description: "Yüzde, yaş ve günlük hesaplamalar",
        color: "from-blue-500 to-indigo-600",
        count: 5,
    },
    {
        id: "e-ticaret",
        name: "E-Ticaret",
        icon: "📦",
        description: "Desi, kâr marjı ve kargo hesaplamaları",
        color: "from-orange-500 to-red-500",
        count: 4,
    },
    {
        id: "saglik",
        name: "Sağlık",
        icon: "❤️",
        description: "BMI, kalori ve sağlık metrikleri hesaplamaları",
        color: "from-pink-500 to-rose-600",
        count: 3,
    },
];
